import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./AppProvider";
import { cookies } from "next/headers";
import ShowModal from "../components/modals/ShowModal";
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const sessionToken = cookieStore.get("jwt");
  return (
    <html lang="en">
      <body className={nunito.className}>
        <AppProvider initialSessionToken={sessionToken?.value}>
          {children}
          <ShowModal />
        </AppProvider>
      </body>
    </html>
  );
}
