import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./AppProvider";
import ShowModal from "../components/modals/ShowModal";
const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SunTravel - The world is yours to explore.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <AppProvider>
          {children}
          <ShowModal />
        </AppProvider>
      </body>
    </html>
  );
}
